apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 7000
  selector:
    app: cassandra
    tier: best-database
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twns-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
      tier: best-database
  strategy:
    type: RollingUpdate
#  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
        tier: best-database
    spec:
      containers:
      - image: cassandra
        name: cassandra
        ports:
        - containerPort: 7000
          name: cassandra
        volumeMounts:
        - name: cassandrapvc
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandrapvc
        persistentVolumeClaim:
          claimName: twns-pvc
