# Defining an API Version
apiVersion: apps/v1

# Defining the kind of application!
kind: ReplicaSet

# Metadata
metadata:
  name: replicaset-from-yml

spec:
  # Declaring the Replica which we desire
  replicas: 3

  # Writing the set based Selector (advantage of ReplicaSet over Replication Controller!)
  selector:
    matchExpressions:
      - {key: DataCenter, operator: In, values: [India] }
      - {key: Environment, operator: In, values: [ Production] }
      - {key: Application, operator: In, values: [Webserver] }

  # Defining the structure of POD to launch!
  template:
    metadata:
      name: mysql-for-wordpress
      labels:
        DataCenter: India
        Environment: Production
        Application: Webserver

    spec:
      containers:
        - name: "mysql-pod-1"
          image: "mysql:5.6"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: blog_database
            - name: MYSQL_USER
              value: HarshitDawar
            - name: MYSQL_PASSWORD
              value: Best_In_The_Universe