# Specifying the APi Version
apiVersion: v1

# Specifying the kind of resource we are deploying
kind: PersistentVolumeClaim

# Specified the metadata(name of the resource in this case)!
metadata:
  name: wp-pvc

# Specification of the container starts here
spec:
  # Specifying the Access Modes!
  accessModes:
    - ReadWriteOnce

  # Specifying the resources!
  resources:
    requests:
      storage: 2G