# Specifying the APi Version
apiVersion: v1

# Specifying the kind of resource we are deploying
kind: PersistentVolumeClaim

metadata:
  name: mypvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G