# Specifying the APi Version
apiVersion: v1

# Specifying the kind of resource we are deploying
kind: PersistentVolumeClaim

# Specified the metadata(name of the resource in this case)!
metadata:
  name: wp-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G