# This is the file which creates a service of Load Balancer behaviour!

# Specifying the API Version
apiVersion: v1

# Specifying the Kind of the service
kind: Service

# Specifying the Metadata
metadata:
  name: lb-for-mysql    # It is for MySQL because the service type used here is clusterIP which does not external connectivity,
  # & it is safe for our database.

spec:
  selector:
    Application: WordPress
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80