# This is the file which creates a service of Load Balancer behaviour!

# Specifying the API Version
apiVersion: v1

# Specifying the Kind of the service
kind: Service

# Specifying the Metadata
metadata:
  name: lb-for-wp   # It is for WordPress as it uses NodePort which provides external connectivity.

spec:
  selector:
    Application: FrontEnd
  type: NodePort
  ports:
    - port: 8081
      nodePort: 32000
      targetPort: 80