# This is the file which creates a service of Load Balancer behaviour!

# Specifying the API Version
apiVersion: v1

# Specifying the Kind of the service
kind: Service

# Specifying the Metadata
metadata:
  name: LB-For-WordPress

spec:
  selector:
    dc: INDIA
